apiVersion: v1
kind: Service
metadata:
  name: fixer-agent
  labels:
    app: fixer-agent
spec:
  type: ClusterIP
  selector:
    app: fixer-agent
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
